console.log(Boolean(10));//Truthy
console.log(Boolean(true));//Truthy
console.log(Boolean(false));//Falsy
console.log(Boolean({}));//Truthy
console.log(Boolean(undefined));//Falsy
console.log(Boolean(null));//Falsy
console.log(Boolean(''));//Falsy
console.log(Boolean('abba'));//Truthy
console.log(Boolean(0));//Falsy